### ISSUE TITLE
Apply for friend link

### ISSUE THREAD

**Issue by bluemiaomiao** [debuginn/blog#159]
最好的存档方式莫过于写文章了。
学了好几天的 Hugo，年底搞一搞移动端适配，哈哈哈。

```yaml
- title: Halo 的主页
  image: https://halo.wecomz.com/favicon-1024x1024.png
  website: https://halo.wecomz.com/?from=blog.debuginn.cn
  description: halo.wecomz.com
```
